---
functional:
  - Пользователь (игрок) может присоединиться к битве из созданного списка другими игроками
  - Пользователь (игрок) может просматривать предстоящие турниры, историю конкурсов, свои турниры и даже создать свой турнир
  - Пользователь (игрок) может общаться в общем чате с другими игроками, но только зарегистрированные пользователи
  - Пользователь (игрок) может видеть текущий онлайн игроков, которые находяться в данный момент на сайте
  - Пользователь (игрок) через пункт меню профиля может просматривать свой профиль (статистику, свои турниры, заверешенные игры, достижения, твое оружие (то есть язык программирования), клан)
  - Пользователь (игрок) через пункт меню профиля может редактировать свой профиль (имя, клан, локаль, тип звука, уровень звука, уровень звука турнира)
  - Пользователь (игрок) через пункт меню профиля может просматривать зал славы (таблицу лидеров текущего сезона, лидеров предыдущего сезона, чемпионов прошлых сезонов)
  - Пользователь (игрок) через пункт меню профиля может просматривать текущие задачи в игре и даже создать новую
  - Пользователь (игрок) через пункт меню профиля может просматривать текущие кланы, сведение о кланах (названия, дата создания, кто создатель и члены клана)
  - Пользователь (игрок) через пункт меню профиля может посмотреть исходный код сайта
  - Пользователь (игрок) через пункт меню профиля можно зайти на сайт https://ru.hexlet.io
  - Пользователь (игрок) через пункт меню профиля можно присоединиться к чату Discord или Телеграмм
  - Пользователь (игрок) через пункт меню профиля может выходить из свой учетной записи
  - Пользователь (игрок) может соревноваться с другом/пользователем/ботом в решении задач и видить написание кода друг у друга, также могут менять язык программирования во время решения
  - Пользователь (игрок) при создании битвы может выбрать уровень сложности
  - Пользователь (игрок) при создании битвы может выбрать тип игры (с кем будет играть), с ботом, с другим пользователем или с другом
  - Пользователь (игрок) при создании битвы может выбрать контроль времени (сколько будет длиться игра)
  - Пользователь (игрок) при создании битвы может выбрать задачу по тегам (например, коллекция, математика, строки и остальное)
  - Другие пользователи могут следить за ходом игры (битвы)
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Система должна предоставлять двум игрокам одинаковую задачу. Победителем объявляется тот, кто первым предоставит корректное решение, успешно проходящее все тесты
  - На сайте любой пользователь (даже неавторизованный) должен иметь возможность зайти в запущенную игру в качестве зрителя и следить за её ходом
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - На сайте должна быть авторизация и регистрация учетной записи
  - Для неавторизованных пользователей доступны только базовые функции, без сохранения прогресса
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - На сайте должна быть проверка уязвимости XSS
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - На сайте решение пользователя должно быть проверено на соответствие тестам задачи и вернуть результат (успех/ошибка)
  - При потере соединения у игрока система должна автоматически переподключаться и восстанавливать состояние текущей игры без потери данных
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию на русский и английский языки
  - На сайте должны быть файлы cookle
implicit:
  - Коллекция задач должна регулярно пополняться и охватывать разные алгоритмические темы и уровни сложности
  - Пользователь должен иметь возможность изменить свой пароль в учетной записи
