---
functional:
  - Пользователь (игрок) может соревноваться с другом/пользователем/ботом в решении задач и видить написание кода друг у друга, также могут менять язык программирования во время решения
  - Пользователь (игрок) при создании битвы может выбрать уровень сложности
  - Пользователь (игрок) при создании битвы может выбрать тип игры (с кем будет играть), с ботом, с другим пользователем или с другом
  - Пользователь (игрок) при создании битвы может выбрать контроль времени (сколько будет длиться игра)
  - Пользователь (игрок) при создании битвы может выбрать задачу по тегам (например, коллекция, математика, строки и остальное)
  - Другие пользователи могут следить за ходом игры (битвы)
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - На сайте должна быть авторизация и регистрация учетной записи
  - Пользователь (игрок) может присоединиться к битве из созданного списка другими игроками
  - Пользователь (игрок) может просматривать предстоящие турниры, историю конкурсов, свои турниры и даже создать свой турнир
  - Пользователь (игрок) может общаться в общем чате с другими игроками
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - требование 5
  - требование 6
